### PR TITLE
Fix/update end for all

### PR DESCRIPTION
**Pull request by Tesa27**
After the counter hit 0 for the host the players that joined later shouldn't be able to continue playing and the game should end for them too.

### CODE REVIEW

**Review by RafaelRamirezS — APPROVED** [review]
all good, logic makes sense to me

**Review by gauthierboeshertz — COMMENTED** [review]
Does the logic make sense? If timers for different players are different it is because some of them took more time to load the map etc.. so should they be penalized? This will also make the timer shown be inaccurate

**Comment by Tesa27** [comment]
> Does the logic make sense? If timers for different players are different it is because some of them took more time to load the map etc.. so should they be penalized? This will also make the timer shown be inaccurate

I think it does since if everyone plays the whole game and a person joins in the last 10 seconds it will still have all the remaining time to play without the rest, and being penalized for a few seconds until the map loads isn't big of a deal.

**Comment by RafaelRamirezS** [comment]
> Does the logic make sense? If timers for different players are different it is because some of them took more time to load the map etc.. so should they be penalized? This will also make the timer shown be inaccurate

I agree with @Tesa27 . It makes sense that the game launches when the host launches it, and it ends when the host is finished. This makes handling the deletion from the DB logic way cleaner, since knowing that everyone has finished playing allows so to delete the game instance from the DB without making anyone crash

**Comment by gauthierboeshertz** [comment]
> I agree with @Tesa27 . It makes sense that the game launches when the host launches it, and it ends when the host is finished. This makes handling the deletion from the DB logic way cleaner, since knowing that everyone has finished playing allows so to delete the game instance from the DB without making anyone crash
> I think it does since if everyone plays the whole game and a person joins in the last 10 seconds it will still have all the remaining time to play without the rest, and being penalized for a few seconds until the map loads isn't big of a deal.

Then maybe we need to add the start_time field to the db?

**Review by Warhedgehog — APPROVED** [review]
Looks good to me

**Pull request merged**
