### PR TITLE
Sign up interface johann

### PR DESCRIPTION
**Pull request by Warhedgehog**
Should be ready for a merge

### CODE REVIEW

**Review by Tesa27 — COMMENTED** [review]
Merge conflicts need to be resolved, and not all 4 tests required for merginf pass

**Review by Tesa27 — COMMENTED** [review]
Good job making the tests pass, but merge conflicts still exist and have to be fixed

**Review by gauthierboeshertz — APPROVED** [review]
Well done!

**Review by Alvaro2112 — APPROVED** [review]
Good job!

**Review by RafaelRamirezS — APPROVED** [review]

**Pull request merged**
