### PR TITLE
Feature/ database can be updated via setters of a player instance

### PR DESCRIPTION
**Pull request by Warhedgehog**

### CODE REVIEW

**Review by Tesa27 — COMMENTED** [review]
No implementation complains, just a quick observation: if 2 concurrent players want to update the database will we have a data race?

**Review by Tesa27 — APPROVED** [review]
Also, it would be more informative to have a description since the name of the commit does not suggest much

**Comment by Warhedgehog** [comment]
> No implementation complains, just a quick observation: if 2 concurrent players want to update the database will we have a data race?

Yes, but I'm not sure if that should ever be the case. Because games may change some attributes and if the player want to change personal info he can but I don't think the sets of attributes in question overlapp

**Comment by Warhedgehog** [comment]
> Is this a draft or a final PR?

It's a final PR

**Comment by Warhedgehog** [comment]
DO NOT MERGE THIS
The player API is changed so other merge would be at risk. I'll overload those methods to prevent that

**Comment by Alvaro2112** [comment]
> DO NOT MERGE THIS
> The player API is changed so other merge would be at risk. I'll overload those methods to prevent that

You could probably convert it into a draft PR to avoid any problems.

**Comment by Warhedgehog** [comment]
Now safe to merge

**Review by gauthierboeshertz — APPROVED** [review]

**Pull request merged**
