### PR TITLE
updated gameID

### PR DESCRIPTION
**Pull request by ArnaudPoletto**
Game ID has now the same ID as the host when creating a new game.

### CODE REVIEW

**Review by gauthierboeshertz — APPROVED** [review]

**Review by Alvaro2112 — CHANGES_REQUESTED** [review]
Did you try this out with the new rules? If so, you should update the rules accordingly.

**Comment by ArnaudPoletto** [comment]
> Did you try this out with the new rules? If so, you should update the rules accordingly.

The rules still fail because it is possible for a user to not be logged in while running some tests.

**Comment by Alvaro2112** [comment]
> > Did you try this out with the new rules? If so, you should update the rules accordingly.
> 
> The rules still fail because it is possible for a user to not be logged in while running some tests.

I see, but wasn't making the rules pass your task? And also, you can isolate the rules that are only related to the GameID to test the modifications you made.

**Comment by ArnaudPoletto** [comment]
> > > Did you try this out with the new rules? If so, you should update the rules accordingly.
> > 
> > 
> > The rules still fail because it is possible for a user to not be logged in while running some tests.
> 
> I see, but wasn't making the rules pass your task? And also, you can isolate the rules that are only related to the GameID to test the modifications you made.

Thanks for the tip. This pull request is not related to the firebase rules. As stated in the description this code changes the game ID and that's it.

**Review by Alvaro2112 — APPROVED** [review]

**Pull request merged**
